# Generated by Django 5.2.4 on 2026-01-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_database',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Father_name', models.CharField(max_length=100)),
                ('Student_cnic', models.CharField(max_length=15, unique=True)),
                ('Father_cnic', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Previous_Qualification', models.CharField(max_length=100)),
                ('Total_marks', models.IntegerField()),
                ('Obtained_marks', models.IntegerField()),
                ('Percentage', models.IntegerField()),
                ('previous_institute', models.CharField(max_length=100)),
                ('selected_program', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
