# Generated by Django 5.2.4 on 2026-01-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_database',
            name='Percentage',
            field=models.CharField(max_length=5),
        ),
    ]
