# Generated by Django 5.2.4 on 2026-02-11 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_engineering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arts', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Arts', to='management.student_database')),
            ],
        ),
        migrations.CreateModel(
            name='ICom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ICom', to='management.student_database')),
            ],
        ),
        migrations.CreateModel(
            name='ICS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ICS', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ICS', to='management.student_database')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medical', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Med', to='management.student_database')),
            ],
        ),
        migrations.CreateModel(
            name='Seience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Seience', to='management.student_database')),
            ],
        ),
    ]
