# Generated by Django 5.2.4 on 2026-03-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_arts_icom_ics_medical_seience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arts',
            old_name='Arts',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='icom',
            old_name='ICom',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='ics',
            old_name='ICS',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='medical',
            old_name='Medical',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='seience',
            old_name='Seience',
            new_name='child',
        ),
    ]
