# Generated by Django 5.2.4 on 2026-03-27 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_arts_arts_child_rename_icom_icom_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ics',
            name='Roll_no',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('ics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ics')),
            ],
        ),
    ]
