# Generated by Django 5.2.4 on 2026-03-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_ics_roll_no_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ics',
            name='Roll_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
