# Generated by Django 5.2.4 on 2026-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_ics_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ics',
            name='Roll_no',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
