# Generated by Django 5.2.4 on 2026-03-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_ics_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ics',
            name='Roll_no',
        ),
    ]
