# Generated by Django 5.2.4 on 2026-04-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_ics_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ics',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
    ]
