# Generated by Django 5.2.4 on 2026-06-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_userauth_remove_ics_roll_no_ics_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_database',
            name='Percentage',
            field=models.CharField(max_length=15),
        ),
    ]
